title: bigbigpark's house
logo: /assets/img/logo.png
name: Park Seong Chang
favicon: true
email: scsc1125@gmail.com

description: For CV, Blog and Project
show_downloads: false

google_analytics: UA-216719934-1 #UA-108144808-1
color-scheme: light # auto/light/dark 
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

remote_theme: BDHU/minimalist